import { Navbar } from "@/components/navbar/Navbar";
import "./globals.css";
import AOSWrapper from "./AOSwrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AOSWrapper>
          <div className="container">
            <Navbar />
            {children}
          </div>
        </AOSWrapper>
      </body>
    </html>
  );
}
